#!/bin/bash
# Notion UI Conversion Script
# This script helps convert your existing Formula PM components to use Notion-style UI

echo "🎨 Formula PM - Notion UI Conversion Script"
echo "=========================================="

# Color definitions
CARAMEL_ESSENCE="#E3AF64"
SAPPHIRE_DUST="#516AC8" 
COSMIC_ODYSSEY="#0F1939"
CLEAN_BACKGROUND="#FBFAF8"

echo ""
echo "📋 Step-by-Step Conversion Guide:"
echo ""

echo "1️⃣  UPDATE MAIN LAYOUT (Already completed ✅)"
echo "   - Your ModernDashboardLayout.jsx is using NotionStyleSidebar"
echo "   - Clean UI CSS is imported in App.jsx"
echo ""

echo "2️⃣  CONVERT PAGES TO USE CleanPageLayout"
echo "   Files to update:"
echo "   □ src/pages/ProjectsPage.jsx"
echo "   □ src/pages/TasksPage.jsx" 
echo "   □ src/pages/TeamPage.jsx"
echo "   □ src/pages/ClientsPage.jsx"
echo "   □ src/pages/ShopDrawingsPage.jsx"
echo "   □ src/pages/MaterialSpecsPage.jsx"
echo ""

echo "3️⃣  UPDATE COMPONENT CLASSES"
echo "   Replace these patterns in all components:"
echo ""
echo "   Cards:"
echo "   OLD: <Card>"
echo "   NEW: <Card className=\"clean-card\">"
echo ""
echo "   Tables:"
echo "   OLD: <TableContainer component={Paper}>"
echo "   NEW: <TableContainer component={Paper} className=\"clean-table\">"
echo ""
echo "   Buttons:"
echo "   OLD: <Button variant=\"contained\">"
echo "   NEW: <Button className=\"clean-button-primary\">"
echo ""
echo "   Chips:"
echo "   OLD: <Chip label={status}>"
echo "   NEW: <Chip label={status} className=\"clean-chip status-in-progress\">"
echo ""
echo "   Progress Bars:"
echo "   OLD: <LinearProgress>"
echo "   NEW: <LinearProgress className=\"clean-progress-bar\">"
echo ""

echo "4️⃣  ADD SECTION HEADERS"
echo "   Replace section titles with:"
echo "   <Box className=\"clean-section-header\">"
echo "     <Box className=\"clean-section-indicator\"></Box>"
echo "     <Typography className=\"clean-section-title\">Section Title</Typography>"
echo "   </Box>"
echo ""

echo "5️⃣  UPDATE EXISTING COMPONENTS"
echo ""

# Function to show file conversion example
show_conversion_example() {
    local file_path=$1
    local component_name=$2
    
    echo "📁 Converting: $file_path"
    echo "   Component: $component_name"
    echo ""
    echo "   Template structure:"
    echo "   import CleanPageLayout, { CleanTab } from '../components/layout/CleanPageLayout';"
    echo ""
    echo "   const headerActions = ("
    echo "     <>"
    echo "       <IconButton className=\"clean-button-secondary\">"
    echo "         <FilterList />"
    echo "       </IconButton>"
    echo "       <Button className=\"clean-button-primary\" startIcon={<Add />}>"
    echo "         Add $component_name"
    echo "       </Button>"
    echo "     </>"
    echo "   );"
    echo ""
    echo "   return ("
    echo "     <CleanPageLayout"
    echo "       title=\"$component_name\""
    echo "       subtitle=\"Manage your construction $component_name\""
    echo "       headerActions={headerActions}"
    echo "       tabs={tabs}"
    echo "     >"
    echo "       {/* Your existing content with clean classes applied */}"
    echo "     </CleanPageLayout>"
    echo "   );"
    echo ""
}

# Show examples for key components
echo "📋 COMPONENT CONVERSION EXAMPLES:"
echo ""

show_conversion_example "src/components/views/ProjectsList.jsx" "Projects"
show_conversion_example "src/components/views/EnhancedTasksView.jsx" "Tasks"
show_conversion_example "src/components/views/TeamMembersList.jsx" "Team Members"

echo "6️⃣  REFERENCE EXAMPLES"
echo "   Check these example files I created:"
echo "   📁 src/components/layout/notion-ui-examples/"
echo "   ├── NotionTasksPage.jsx (Complete tasks page example)"
echo "   ├── NotionTeamPage.jsx (Complete team page example)"
echo "   └── ProjectOverviewPage.jsx (Complete projects overview)"
echo ""

echo "7️⃣  CSS CLASSES REFERENCE"
echo "   Available clean UI classes:"
echo "   🎨 Layout:"
echo "      .clean-card - Clean card styling"
echo "      .clean-table - Clean table styling"
echo "      .clean-section-header - Section headers"
echo "      .clean-section-title - Section titles"
echo "      .clean-section-indicator - Colored indicators"
echo ""
echo "   🎨 Interactive:"
echo "      .clean-button-primary - Primary buttons ($CARAMEL_ESSENCE)"
echo "      .clean-button-secondary - Secondary buttons"
echo "      .clean-input - Input fields"
echo "      .clean-select - Select dropdowns"
echo ""
echo "   🎨 Status:"
echo "      .clean-chip - Base chip styling"
echo "      .status-completed - Green status (completed)"
echo "      .status-in-progress - Orange status (in progress)"  
echo "      .status-review - Blue status (review/planning)"
echo "      .status-todo - Gray status (todo/on-hold)"
echo ""
echo "   🎨 Components:"
echo "      .clean-progress-bar - Progress indicators"
echo "      .clean-avatar-group - Avatar groups"
echo "      .clean-fade-in - Fade in animation"
echo "      .clean-scrollbar - Custom scrollbars"
echo ""

echo "8️⃣  TESTING CHECKLIST"
echo "   After conversion, verify:"
echo "   □ All pages use CleanPageLayout"
echo "   □ Cards have clean-card class"
echo "   □ Tables have clean-table class"
echo "   □ Buttons use clean button classes"
echo "   □ Status chips use appropriate status classes"
echo "   □ Colors match your brand palette"
echo "   □ Mobile responsiveness works"
echo "   □ Animations are smooth"
echo ""

echo "9️⃣  CONSTRUCTION-SPECIFIC FEATURES"
echo "   Your clean UI includes construction-focused elements:"
echo "   🏗️  Project progress tracking with visual indicators"
echo "   📋 Task management with priority and status"
echo "   👷 Team workload distribution"
echo "   📊 Budget and timeline visualization"
echo "   📐 Shop drawings and specifications"
echo "   🔧 Material and procurement tracking"
echo ""

echo "🎯 NEXT STEPS:"
echo "1. Start with one page (e.g., Projects)"
echo "2. Apply CleanPageLayout wrapper"
echo "3. Update all classes to use clean- prefixes"
echo "4. Test the page thoroughly"
echo "5. Move to the next page"
echo "6. Repeat until all pages are converted"
echo ""

echo "💡 PRO TIPS:"
echo "• Use the example files as templates"
echo "• Keep your existing functionality - just update the UI"
echo "• Test on mobile devices during conversion"
echo "• Ask for help if you get stuck on any component"
echo ""

echo "✨ Your Formula PM app will have a professional,"
echo "   Notion-style interface perfect for construction management!"
echo ""
echo "=========================================="
echo "🚀 Ready to start the conversion!"