version: '3.8'

services:
  # React Frontend Service
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: development
    ports:
      - "3000:3000"
    volumes:
      # Use bind mounts for development with optimizations
      - ../formula-project-app:/app
      # Use named volume for node_modules for better performance
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - GENERATE_SOURCEMAP=false
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Node.js Backend Service  
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5001:5001"
    volumes:
      - ../formula-backend:/app
      - backend_node_modules:/app/node_modules
      # Persist database files
      - backend_data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=5001
    restart: unless-stopped

volumes:
  # Named volumes for better performance
  frontend_node_modules:
    driver: local
  backend_node_modules:
    driver: local
  backend_data:
    driver: local

networks:
  default:
    driver: bridge