// Demo data service for development and testing
// This provides mock data when the backend is not available

export const demoProjects = [
  // Commercial Projects
  {
    id: 'proj-1',
    name: 'Westfield Shopping Center Renovation',
    type: 'commercial',
    status: 'active',
    priority: 'urgent',
    description: 'Major renovation of 50,000 sq ft shopping center including custom storefronts, kiosks, and luxury retail millwork',
    budget: 2800000,
    startDate: '2024-01-05',
    endDate: '2024-08-30',
    progress: 68,
    clientId: 'client-1',
    projectManager: 'team-1',
    teamMembers: ['team-1', 'team-2', 'team-3', 'team-7', 'team-8'],
    location: '1234 Commerce Blvd, Westfield',
    contractNumber: 'WSC-2024-001',
    scopeItems: 15,
    shopDrawings: 8,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-06-28T14:30:00Z'
  },
  {
    id: 'proj-2',
    name: 'Tech Campus Office Buildout',
    type: 'commercial',
    status: 'active',
    priority: 'high',
    description: 'Modern tech office with custom workstations, conference room millwork, and innovative collaborative spaces',
    budget: 950000,
    startDate: '2024-02-15',
    endDate: '2024-07-15',
    progress: 82,
    clientId: 'client-5',
    projectManager: 'team-2',
    teamMembers: ['team-2', 'team-4', 'team-9', 'team-13'],
    location: '500 Innovation Drive, Tech Park',
    contractNumber: 'TCP-2024-002',
    scopeItems: 12,
    shopDrawings: 6,
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-06-29T11:00:00Z'
  },
  {
    id: 'proj-3',
    name: 'Medical Plaza Construction',
    type: 'commercial',
    status: 'active',
    priority: 'high',
    description: 'Healthcare facility with specialized medical casework, nurse stations, and patient room millwork',
    budget: 3200000,
    startDate: '2024-01-20',
    endDate: '2024-09-30',
    progress: 45,
    clientId: 'client-3',
    projectManager: 'team-3',
    teamMembers: ['team-3', 'team-5', 'team-10', 'team-14', 'team-15'],
    location: '789 Healthcare Pkwy, Medical District',
    contractNumber: 'MPC-2024-003',
    scopeItems: 18,
    shopDrawings: 12,
    createdAt: '2024-01-10T11:00:00Z',
    updatedAt: '2024-06-30T09:00:00Z'
  },
  {
    id: 'proj-4',
    name: 'Downtown Hotel Lobby Renovation',
    type: 'commercial',
    status: 'active',
    priority: 'high',
    description: 'Luxury hotel lobby renovation with custom reception desk, concierge stations, and decorative wall panels',
    budget: 1500000,
    startDate: '2024-03-01',
    endDate: '2024-08-15',
    progress: 35,
    clientId: 'client-4',
    projectManager: 'team-1',
    teamMembers: ['team-1', 'team-6', 'team-11', 'team-16'],
    location: '100 Luxury Lane, Downtown',
    contractNumber: 'DHL-2024-004',
    scopeItems: 10,
    shopDrawings: 5,
    createdAt: '2024-02-20T08:00:00Z',
    updatedAt: '2024-06-29T16:00:00Z'
  },
  {
    id: 'proj-5',
    name: 'Corporate Headquarters Expansion',
    type: 'commercial',
    status: 'active',
    priority: 'urgent',
    description: 'Executive floor buildout with boardroom millwork, executive offices, and high-end finishes',
    budget: 4100000,
    startDate: '2024-01-10',
    endDate: '2024-10-30',
    progress: 55,
    clientId: 'client-1',
    projectManager: 'team-1',
    teamMembers: ['team-1', 'team-2', 'team-3', 'team-7', 'team-12', 'team-17'],
    location: '2000 Corporate Blvd, Financial District',
    contractNumber: 'CHE-2024-005',
    scopeItems: 22,
    shopDrawings: 15,
    createdAt: '2024-01-05T12:00:00Z',
    updatedAt: '2024-06-30T10:00:00Z'
  },
  // Residential Projects
  {
    id: 'proj-6',
    name: 'Luxury Waterfront Estate',
    type: 'residential',
    status: 'active',
    priority: 'high',
    description: 'Custom millwork throughout 8,000 sq ft waterfront home including library, wine cellar, and entertainment center',
    budget: 650000,
    startDate: '2024-02-20',
    endDate: '2024-07-30',
    progress: 60,
    clientId: 'client-6',
    projectManager: 'team-2',
    teamMembers: ['team-2', 'team-8', 'team-13', 'team-18'],
    location: '45 Oceanview Drive, Coastal Heights',
    contractNumber: 'LWE-2024-006',
    scopeItems: 14,
    shopDrawings: 9,
    createdAt: '2024-02-10T09:00:00Z',
    updatedAt: '2024-06-29T14:00:00Z'
  },
  {
    id: 'proj-7',
    name: 'Modern Penthouse Renovation',
    type: 'residential',
    status: 'active',
    priority: 'medium',
    description: 'Contemporary penthouse with custom kitchen, built-in entertainment units, and architectural features',
    budget: 420000,
    startDate: '2024-03-15',
    endDate: '2024-07-15',
    progress: 40,
    clientId: 'client-7',
    projectManager: 'team-3',
    teamMembers: ['team-3', 'team-9', 'team-14'],
    location: '3000 Skyline Tower, Unit PH-A',
    contractNumber: 'MPR-2024-007',
    scopeItems: 8,
    shopDrawings: 4,
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-06-28T13:00:00Z'
  },
  {
    id: 'proj-8',
    name: 'Historic Mansion Restoration',
    type: 'residential',
    status: 'on-tender',
    priority: 'high',
    description: 'Restoration of 1920s mansion with period-appropriate millwork, custom moldings, and specialty finishes',
    budget: 880000,
    startDate: '2024-07-01',
    endDate: '2024-12-30',
    progress: 0,
    clientId: 'client-8',
    projectManager: 'team-1',
    teamMembers: ['team-1', 'team-4', 'team-10', 'team-15'],
    location: '789 Heritage Hill Road',
    contractNumber: 'HMR-2024-008',
    scopeItems: 16,
    shopDrawings: 0,
    createdAt: '2024-06-15T11:00:00Z',
    updatedAt: '2024-06-28T11:00:00Z'
  },
  // Specialty Projects
  {
    id: 'proj-9',
    name: 'Museum Gallery Millwork',
    type: 'commercial',
    status: 'active',
    priority: 'medium',
    description: 'Custom display cases, wall systems, and specialized lighting integration for art gallery',
    budget: 520000,
    startDate: '2024-04-01',
    endDate: '2024-08-30',
    progress: 25,
    clientId: 'client-9',
    projectManager: 'team-2',
    teamMembers: ['team-2', 'team-5', 'team-11', 'team-16'],
    location: '456 Culture Center, Arts District',
    contractNumber: 'MGM-2024-009',
    scopeItems: 9,
    shopDrawings: 3,
    createdAt: '2024-03-20T09:00:00Z',
    updatedAt: '2024-06-30T08:00:00Z'
  },
  {
    id: 'proj-10',
    name: 'Restaurant Chain Prototype',
    type: 'commercial',
    status: 'completed',
    priority: 'medium',
    description: 'Prototype restaurant design with modular millwork system for nationwide rollout',
    budget: 380000,
    startDate: '2024-01-15',
    endDate: '2024-05-30',
    progress: 100,
    clientId: 'client-10',
    projectManager: 'team-3',
    teamMembers: ['team-3', 'team-6', 'team-12', 'team-17'],
    location: '123 Franchise Way, Business Park',
    contractNumber: 'RCP-2024-010',
    scopeItems: 11,
    shopDrawings: 7,
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-05-30T17:00:00Z'
  }
];

export const demoTasks = [
  // Westfield Shopping Center Tasks
  {
    id: 'task-1',
    projectId: 'proj-1',
    name: 'Storefront Design Approval',
    title: 'Storefront Design Approval',
    description: 'Finalize and approve storefront designs for all retail tenants',
    status: 'completed',
    priority: 'high',
    assignedTo: 'team-2',
    dueDate: '2024-02-15',
    createdAt: '2024-01-15T10:00:00Z',
    completedAt: '2024-02-14T16:00:00Z'
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    name: 'Material Procurement - Phase 1',
    title: 'Material Procurement - Phase 1',
    description: 'Order premium wood veneers and hardware for luxury stores',
    status: 'completed',
    priority: 'urgent',
    assignedTo: 'team-3',
    dueDate: '2024-02-20',
    createdAt: '2024-01-20T09:00:00Z',
    completedAt: '2024-02-18T14:00:00Z'
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    name: 'Install Center Court Kiosks',
    title: 'Install Center Court Kiosks',
    description: 'Fabricate and install 4 custom retail kiosks in center court',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'team-7',
    dueDate: '2024-07-15',
    createdAt: '2024-06-01T08:00:00Z'
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    name: 'Luxury Brand Store Millwork',
    title: 'Luxury Brand Store Millwork',
    description: 'Custom millwork for flagship luxury brand store',
    status: 'in-progress',
    priority: 'urgent',
    assignedTo: 'team-8',
    dueDate: '2024-07-30',
    createdAt: '2024-06-10T10:00:00Z'
  },
  {
    id: 'task-5',
    projectId: 'proj-1',
    name: 'Food Court Renovation',
    title: 'Food Court Renovation',
    description: 'Update food court with modern seating and serving counters',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'team-2',
    dueDate: '2024-08-15',
    createdAt: '2024-06-20T11:00:00Z'
  },
  // Tech Campus Tasks
  {
    id: 'task-6',
    projectId: 'proj-2',
    name: 'Open Office Workstations',
    title: 'Open Office Workstations',
    description: 'Build and install 50 modular workstations with cable management',
    status: 'completed',
    priority: 'high',
    assignedTo: 'team-4',
    dueDate: '2024-04-30',
    createdAt: '2024-03-01T09:00:00Z',
    completedAt: '2024-04-28T17:00:00Z'
  },
  {
    id: 'task-7',
    projectId: 'proj-2',
    name: 'Executive Conference Room',
    title: 'Executive Conference Room',
    description: 'Custom conference table and AV integration millwork',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'team-9',
    dueDate: '2024-07-01',
    createdAt: '2024-06-15T10:00:00Z'
  },
  {
    id: 'task-8',
    projectId: 'proj-2',
    name: 'Collaborative Areas',
    title: 'Collaborative Areas',
    description: 'Install phone booths and collaboration pods',
    status: 'in-progress',
    priority: 'medium',
    assignedTo: 'team-13',
    dueDate: '2024-07-10',
    createdAt: '2024-06-20T08:00:00Z'
  },
  // Medical Plaza Tasks
  {
    id: 'task-9',
    projectId: 'proj-3',
    name: 'Nurse Station Fabrication',
    title: 'Nurse Station Fabrication',
    description: 'Fabricate custom nurse stations for all floors',
    status: 'in-progress',
    priority: 'urgent',
    assignedTo: 'team-5',
    dueDate: '2024-07-30',
    createdAt: '2024-06-01T09:00:00Z'
  },
  {
    id: 'task-10',
    projectId: 'proj-3',
    name: 'Patient Room Casework',
    title: 'Patient Room Casework',
    description: 'Install medical-grade casework in 50 patient rooms',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'team-10',
    dueDate: '2024-08-15',
    createdAt: '2024-06-10T10:00:00Z'
  },
  {
    id: 'task-11',
    projectId: 'proj-3',
    name: 'Pharmacy Millwork',
    title: 'Pharmacy Millwork',
    description: 'Specialized millwork for secure pharmacy storage',
    status: 'pending',
    priority: 'high',
    assignedTo: 'team-14',
    dueDate: '2024-08-30',
    createdAt: '2024-06-15T11:00:00Z'
  },
  {
    id: 'task-12',
    projectId: 'proj-3',
    name: 'Lab Casework Installation',
    title: 'Lab Casework Installation',
    description: 'Chemical-resistant lab casework and fume hoods',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'team-15',
    dueDate: '2024-09-15',
    createdAt: '2024-06-20T14:00:00Z'
  },
  // Hotel Lobby Tasks
  {
    id: 'task-13',
    projectId: 'proj-4',
    name: 'Reception Desk Design',
    title: 'Reception Desk Design',
    description: 'Design curved reception desk with backlit onyx panels',
    status: 'completed',
    priority: 'high',
    assignedTo: 'team-6',
    dueDate: '2024-04-15',
    createdAt: '2024-03-15T09:00:00Z',
    completedAt: '2024-04-10T16:00:00Z'
  },
  {
    id: 'task-14',
    projectId: 'proj-4',
    name: 'Concierge Station Build',
    title: 'Concierge Station Build',
    description: 'Fabricate and install marble-top concierge desks',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'team-11',
    dueDate: '2024-07-20',
    createdAt: '2024-06-25T10:00:00Z'
  },
  {
    id: 'task-15',
    projectId: 'proj-4',
    name: 'Feature Wall Installation',
    title: 'Feature Wall Installation',
    description: 'Install decorative wood panel feature wall behind reception',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'team-16',
    dueDate: '2024-08-01',
    createdAt: '2024-06-28T11:00:00Z'
  },
  // Corporate HQ Tasks
  {
    id: 'task-16',
    projectId: 'proj-5',
    name: 'Boardroom Table',
    title: 'Boardroom Table',
    description: '30-foot custom boardroom table with integrated technology',
    status: 'in-progress',
    priority: 'urgent',
    assignedTo: 'team-12',
    dueDate: '2024-08-01',
    createdAt: '2024-06-01T09:00:00Z'
  },
  {
    id: 'task-17',
    projectId: 'proj-5',
    name: 'Executive Office Suites',
    title: 'Executive Office Suites',
    description: 'Custom millwork for 10 executive offices',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'team-17',
    dueDate: '2024-09-01',
    createdAt: '2024-06-15T10:00:00Z'
  },
  {
    id: 'task-18',
    projectId: 'proj-5',
    name: 'Reception Area Millwork',
    title: 'Reception Area Millwork',
    description: 'Grand reception desk and waiting area furniture',
    status: 'completed',
    priority: 'high',
    assignedTo: 'team-7',
    dueDate: '2024-05-30',
    createdAt: '2024-04-01T08:00:00Z',
    completedAt: '2024-05-28T17:00:00Z'
  },
  // Waterfront Estate Tasks
  {
    id: 'task-19',
    projectId: 'proj-6',
    name: 'Library Built-ins',
    title: 'Library Built-ins',
    description: 'Floor-to-ceiling walnut library with ladder system',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'team-8',
    dueDate: '2024-07-15',
    createdAt: '2024-06-01T09:00:00Z'
  },
  {
    id: 'task-20',
    projectId: 'proj-6',
    name: 'Wine Cellar Construction',
    title: 'Wine Cellar Construction',
    description: 'Climate-controlled wine storage for 2000 bottles',
    status: 'in-progress',
    priority: 'medium',
    assignedTo: 'team-13',
    dueDate: '2024-07-25',
    createdAt: '2024-06-10T10:00:00Z'
  },
  {
    id: 'task-21',
    projectId: 'proj-6',
    name: 'Master Suite Millwork',
    title: 'Master Suite Millwork',
    description: 'Custom closet systems and bedroom built-ins',
    status: 'completed',
    priority: 'high',
    assignedTo: 'team-18',
    dueDate: '2024-05-30',
    createdAt: '2024-04-15T08:00:00Z',
    completedAt: '2024-05-28T16:00:00Z'
  },
  // Penthouse Tasks
  {
    id: 'task-22',
    projectId: 'proj-7',
    name: 'Kitchen Cabinet Installation',
    title: 'Kitchen Cabinet Installation',
    description: 'Install high-gloss custom kitchen with integrated appliances',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'team-9',
    dueDate: '2024-07-01',
    createdAt: '2024-06-15T09:00:00Z'
  },
  {
    id: 'task-23',
    projectId: 'proj-7',
    name: 'Entertainment Center',
    title: 'Entertainment Center',
    description: 'Built-in media center with hidden storage',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'team-14',
    dueDate: '2024-07-10',
    createdAt: '2024-06-20T10:00:00Z'
  },
  // Museum Tasks
  {
    id: 'task-24',
    projectId: 'proj-9',
    name: 'Display Case Fabrication',
    title: 'Display Case Fabrication',
    description: 'Museum-quality display cases with security features',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'team-5',
    dueDate: '2024-08-01',
    createdAt: '2024-06-25T09:00:00Z'
  },
  {
    id: 'task-25',
    projectId: 'proj-9',
    name: 'Wall System Installation',
    title: 'Wall System Installation',
    description: 'Modular wall system for changing exhibitions',
    status: 'pending',
    priority: 'medium',
    assignedTo: 'team-11',
    dueDate: '2024-08-20',
    createdAt: '2024-06-28T11:00:00Z'
  },
  // Restaurant Prototype Tasks
  {
    id: 'task-26',
    projectId: 'proj-10',
    name: 'Modular Seating System',
    title: 'Modular Seating System',
    description: 'Design and test modular booth seating',
    status: 'completed',
    priority: 'high',
    assignedTo: 'team-6',
    dueDate: '2024-03-30',
    createdAt: '2024-02-15T09:00:00Z',
    completedAt: '2024-03-28T17:00:00Z'
  },
  {
    id: 'task-27',
    projectId: 'proj-10',
    name: 'Kitchen Pass-through',
    title: 'Kitchen Pass-through',
    description: 'Stainless steel pass-through with warming lights',
    status: 'completed',
    priority: 'medium',
    assignedTo: 'team-12',
    dueDate: '2024-04-15',
    createdAt: '2024-03-01T10:00:00Z',
    completedAt: '2024-04-12T16:00:00Z'
  }
];

export const demoTeamMembers = [
  // Project Managers
  {
    id: 'team-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    fullName: 'Sarah Johnson',
    initials: 'SJ',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@formulapm.com',
    role: 'project_manager',
    position: 'Senior Project Manager',
    department: 'Project Management',
    phone: '+1 (555) 123-4567',
    avatar: 'https://i.pravatar.cc/150?img=1',
    status: 'active',
    joinDate: '2022-03-15',
    skills: ['Project Management', 'Millwork Design', 'Client Relations', 'Budget Management'],
    certifications: ['PMP', 'LEED AP'],
    yearsExperience: 12
  },
  {
    id: 'team-2',
    firstName: 'Michael',
    lastName: 'Chen',
    fullName: 'Michael Chen',
    initials: 'MC',
    name: 'Michael Chen',
    email: 'michael.chen@formulapm.com',
    role: 'project_manager',
    position: 'Project Manager',
    department: 'Project Management',
    phone: '+1 (555) 123-4568',
    avatar: 'https://i.pravatar.cc/150?img=2',
    status: 'active',
    joinDate: '2023-01-10',
    skills: ['Commercial Projects', 'Team Leadership', 'Scheduling'],
    certifications: ['PMP'],
    yearsExperience: 8
  },
  {
    id: 'team-3',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    fullName: 'Emily Rodriguez',
    initials: 'ER',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@formulapm.com',
    role: 'project_manager',
    position: 'Project Manager',
    department: 'Project Management',
    phone: '+1 (555) 123-4569',
    avatar: 'https://i.pravatar.cc/150?img=5',
    status: 'active',
    joinDate: '2023-06-20',
    skills: ['Residential Projects', 'Design Coordination', 'Quality Control'],
    certifications: ['CAPM'],
    yearsExperience: 6
  },
  // Site Supervisors
  {
    id: 'team-4',
    firstName: 'David',
    lastName: 'Thompson',
    fullName: 'David Thompson',
    initials: 'DT',
    name: 'David Thompson',
    email: 'david.thompson@formulapm.com',
    role: 'supervisor',
    position: 'Senior Site Supervisor',
    department: 'Field Operations',
    phone: '+1 (555) 123-4570',
    avatar: 'https://i.pravatar.cc/150?img=3',
    status: 'active',
    joinDate: '2021-11-05',
    skills: ['Site Management', 'Safety Compliance', 'Team Coordination'],
    certifications: ['OSHA 30'],
    yearsExperience: 15
  },
  {
    id: 'team-5',
    firstName: 'Robert',
    lastName: 'Wilson',
    fullName: 'Robert Wilson',
    initials: 'RW',
    name: 'Robert Wilson',
    email: 'robert.wilson@formulapm.com',
    role: 'supervisor',
    position: 'Site Supervisor',
    department: 'Field Operations',
    phone: '+1 (555) 123-4571',
    avatar: 'https://i.pravatar.cc/150?img=7',
    status: 'active',
    joinDate: '2022-08-12',
    skills: ['Installation Oversight', 'Quality Assurance', 'Problem Solving'],
    certifications: ['OSHA 10'],
    yearsExperience: 10
  },
  {
    id: 'team-6',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    fullName: 'Jennifer Martinez',
    initials: 'JM',
    name: 'Jennifer Martinez',
    email: 'jennifer.martinez@formulapm.com',
    role: 'supervisor',
    position: 'Site Supervisor',
    department: 'Field Operations',
    phone: '+1 (555) 123-4572',
    avatar: 'https://i.pravatar.cc/150?img=9',
    status: 'active',
    joinDate: '2023-02-28',
    skills: ['Field Coordination', 'Scheduling', 'Client Communication'],
    certifications: ['OSHA 10'],
    yearsExperience: 7
  },
  {
    id: 'team-7',
    firstName: 'James',
    lastName: 'Anderson',
    fullName: 'James Anderson',
    initials: 'JA',
    name: 'James Anderson',
    email: 'james.anderson@formulapm.com',
    role: 'supervisor',
    position: 'Night Shift Supervisor',
    department: 'Field Operations',
    phone: '+1 (555) 123-4573',
    avatar: 'https://i.pravatar.cc/150?img=11',
    status: 'active',
    joinDate: '2022-05-17',
    skills: ['Night Operations', 'Emergency Response', 'Team Management'],
    certifications: ['OSHA 30', 'First Aid'],
    yearsExperience: 9
  },
  // Lead Carpenters
  {
    id: 'team-8',
    firstName: 'William',
    lastName: 'Brown',
    fullName: 'William Brown',
    initials: 'WB',
    name: 'William Brown',
    email: 'william.brown@formulapm.com',
    role: 'carpenter',
    position: 'Lead Carpenter',
    department: 'Production',
    phone: '+1 (555) 123-4574',
    avatar: 'https://i.pravatar.cc/150?img=12',
    status: 'active',
    joinDate: '2021-09-03',
    skills: ['Custom Millwork', 'Finishing', 'Tool Operation'],
    certifications: ['Master Carpenter'],
    yearsExperience: 18
  },
  {
    id: 'team-9',
    firstName: 'Christopher',
    lastName: 'Davis',
    fullName: 'Christopher Davis',
    initials: 'CD',
    name: 'Christopher Davis',
    email: 'christopher.davis@formulapm.com',
    role: 'carpenter',
    position: 'Lead Carpenter',
    department: 'Production',
    phone: '+1 (555) 123-4575',
    avatar: 'https://i.pravatar.cc/150?img=13',
    status: 'active',
    joinDate: '2022-01-20',
    skills: ['Cabinetry', 'Installation', 'Blueprint Reading'],
    certifications: ['Journeyman'],
    yearsExperience: 12
  },
  {
    id: 'team-10',
    firstName: 'Maria',
    lastName: 'Garcia',
    fullName: 'Maria Garcia',
    initials: 'MG',
    name: 'Maria Garcia',
    email: 'maria.garcia@formulapm.com',
    role: 'carpenter',
    position: 'Lead Carpenter',
    department: 'Production',
    phone: '+1 (555) 123-4576',
    avatar: 'https://i.pravatar.cc/150?img=20',
    status: 'active',
    joinDate: '2022-07-08',
    skills: ['Fine Woodworking', 'Restoration', 'Team Training'],
    certifications: ['Master Carpenter'],
    yearsExperience: 14
  },
  // Millwork Specialists
  {
    id: 'team-11',
    firstName: 'Thomas',
    lastName: 'Miller',
    fullName: 'Thomas Miller',
    initials: 'TM',
    name: 'Thomas Miller',
    email: 'thomas.miller@formulapm.com',
    role: 'specialist',
    position: 'Millwork Specialist',
    department: 'Production',
    phone: '+1 (555) 123-4577',
    avatar: 'https://i.pravatar.cc/150?img=15',
    status: 'active',
    joinDate: '2023-03-12',
    skills: ['CNC Operation', 'Veneer Application', 'Custom Design'],
    certifications: ['CNC Certified'],
    yearsExperience: 10
  },
  {
    id: 'team-12',
    firstName: 'Lisa',
    lastName: 'Taylor',
    fullName: 'Lisa Taylor',
    initials: 'LT',
    name: 'Lisa Taylor',
    email: 'lisa.taylor@formulapm.com',
    role: 'specialist',
    position: 'Finishing Specialist',
    department: 'Production',
    phone: '+1 (555) 123-4578',
    avatar: 'https://i.pravatar.cc/150?img=23',
    status: 'active',
    joinDate: '2022-10-25',
    skills: ['Staining', 'Lacquer Application', 'Color Matching'],
    certifications: ['Finishing Expert'],
    yearsExperience: 8
  },
  // CAD Designers
  {
    id: 'team-13',
    firstName: 'Daniel',
    lastName: 'Moore',
    fullName: 'Daniel Moore',
    initials: 'DM',
    name: 'Daniel Moore',
    email: 'daniel.moore@formulapm.com',
    role: 'designer',
    position: 'Senior CAD Designer',
    department: 'Design',
    phone: '+1 (555) 123-4579',
    avatar: 'https://i.pravatar.cc/150?img=17',
    status: 'active',
    joinDate: '2021-06-14',
    skills: ['AutoCAD', '3D Modeling', 'Shop Drawings'],
    certifications: ['AutoCAD Professional'],
    yearsExperience: 11
  },
  {
    id: 'team-14',
    firstName: 'Jessica',
    lastName: 'White',
    fullName: 'Jessica White',
    initials: 'JW',
    name: 'Jessica White',
    email: 'jessica.white@formulapm.com',
    role: 'designer',
    position: 'CAD Designer',
    department: 'Design',
    phone: '+1 (555) 123-4580',
    avatar: 'https://i.pravatar.cc/150?img=25',
    status: 'active',
    joinDate: '2023-04-18',
    skills: ['Revit', 'SketchUp', 'Technical Drawing'],
    certifications: ['Revit Certified'],
    yearsExperience: 5
  },
  // Project Coordinators
  {
    id: 'team-15',
    firstName: 'Kevin',
    lastName: 'Harris',
    fullName: 'Kevin Harris',
    initials: 'KH',
    name: 'Kevin Harris',
    email: 'kevin.harris@formulapm.com',
    role: 'coordinator',
    position: 'Senior Project Coordinator',
    department: 'Administration',
    phone: '+1 (555) 123-4581',
    avatar: 'https://i.pravatar.cc/150?img=18',
    status: 'active',
    joinDate: '2022-02-07',
    skills: ['Documentation', 'Scheduling', 'Vendor Management'],
    certifications: ['PMI-ACP'],
    yearsExperience: 7
  },
  {
    id: 'team-16',
    firstName: 'Amanda',
    lastName: 'Clark',
    fullName: 'Amanda Clark',
    initials: 'AC',
    name: 'Amanda Clark',
    email: 'amanda.clark@formulapm.com',
    role: 'coordinator',
    position: 'Project Coordinator',
    department: 'Administration',
    phone: '+1 (555) 123-4582',
    avatar: 'https://i.pravatar.cc/150?img=27',
    status: 'active',
    joinDate: '2023-08-22',
    skills: ['Communication', 'Report Writing', 'Data Analysis'],
    certifications: [],
    yearsExperience: 3
  },
  // Safety Manager
  {
    id: 'team-17',
    firstName: 'Richard',
    lastName: 'Lewis',
    fullName: 'Richard Lewis',
    initials: 'RL',
    name: 'Richard Lewis',
    email: 'richard.lewis@formulapm.com',
    role: 'safety',
    position: 'Safety Manager',
    department: 'Safety & Compliance',
    phone: '+1 (555) 123-4583',
    avatar: 'https://i.pravatar.cc/150?img=19',
    status: 'active',
    joinDate: '2021-04-11',
    skills: ['Safety Training', 'OSHA Compliance', 'Risk Assessment'],
    certifications: ['CSP', 'OSHA 500'],
    yearsExperience: 16
  },
  // Quality Control Manager
  {
    id: 'team-18',
    firstName: 'Patricia',
    lastName: 'Walker',
    fullName: 'Patricia Walker',
    initials: 'PW',
    name: 'Patricia Walker',
    email: 'patricia.walker@formulapm.com',
    role: 'quality',
    position: 'Quality Control Manager',
    department: 'Quality Assurance',
    phone: '+1 (555) 123-4584',
    avatar: 'https://i.pravatar.cc/150?img=28',
    status: 'active',
    joinDate: '2022-09-05',
    skills: ['Quality Inspection', 'Standards Compliance', 'Process Improvement'],
    certifications: ['CQE', 'Six Sigma'],
    yearsExperience: 13
  },
  // Junior Carpenters
  {
    id: 'team-19',
    firstName: 'Joseph',
    lastName: 'Hall',
    fullName: 'Joseph Hall',
    initials: 'JH',
    name: 'Joseph Hall',
    email: 'joseph.hall@formulapm.com',
    role: 'carpenter',
    position: 'Junior Carpenter',
    department: 'Production',
    phone: '+1 (555) 123-4585',
    avatar: 'https://i.pravatar.cc/150?img=22',
    status: 'active',
    joinDate: '2024-01-15',
    skills: ['Basic Carpentry', 'Tool Maintenance', 'Material Handling'],
    certifications: ['Apprentice'],
    yearsExperience: 2
  },
  {
    id: 'team-20',
    firstName: 'Ashley',
    lastName: 'Young',
    fullName: 'Ashley Young',
    initials: 'AY',
    name: 'Ashley Young',
    email: 'ashley.young@formulapm.com',
    role: 'carpenter',
    position: 'Junior Carpenter',
    department: 'Production',
    phone: '+1 (555) 123-4586',
    avatar: 'https://i.pravatar.cc/150?img=30',
    status: 'active',
    joinDate: '2024-02-20',
    skills: ['Assembly', 'Sanding', 'Basic Installation'],
    certifications: ['Apprentice'],
    yearsExperience: 1
  }
];

export const demoClients = [
  {
    id: 'client-1',
    name: 'Westfield Properties Group',
    type: 'Commercial Developer',
    email: 'contact@westfieldproperties.com',
    phone: '+1 (555) 234-5678',
    address: '100 Commerce Tower, Suite 2000, Downtown',
    contactPerson: 'James Mitchell',
    status: 'active',
    projects: 2,
    totalBudget: 6900000,
    createdAt: '2023-06-15T10:00:00Z'
  },
  {
    id: 'client-2',
    name: 'Elite Residential Developers',
    type: 'Residential Developer',
    email: 'info@eliteresidential.com',
    phone: '+1 (555) 234-5679',
    address: '45 Luxury Lane, Uptown District',
    contactPerson: 'Victoria Chen',
    status: 'active',
    projects: 1,
    totalBudget: 220000,
    createdAt: '2023-08-20T11:00:00Z'
  },
  {
    id: 'client-3',
    name: 'Healthcare Facilities Inc',
    type: 'Healthcare',
    email: 'facilities@healthcareinc.com',
    phone: '+1 (555) 234-5680',
    address: '789 Medical Center Blvd',
    contactPerson: 'Dr. Robert Anderson',
    status: 'active',
    projects: 1,
    totalBudget: 3200000,
    createdAt: '2023-09-10T09:00:00Z'
  },
  {
    id: 'client-4',
    name: 'Luxury Hotels International',
    type: 'Hospitality',
    email: 'projects@luxuryhotels.com',
    phone: '+1 (555) 234-5681',
    address: '1 Hotel Plaza, Downtown',
    contactPerson: 'Maria Rodriguez',
    status: 'active',
    projects: 1,
    totalBudget: 1500000,
    createdAt: '2023-10-05T14:00:00Z'
  },
  {
    id: 'client-5',
    name: 'TechCorp Industries',
    type: 'Technology',
    email: 'facilities@techcorp.com',
    phone: '+1 (555) 234-5682',
    address: '500 Innovation Drive, Tech Park',
    contactPerson: 'David Kim',
    status: 'active',
    projects: 1,
    totalBudget: 950000,
    createdAt: '2023-11-12T10:00:00Z'
  },
  {
    id: 'client-6',
    name: 'Private Estate Holdings',
    type: 'Private Client',
    email: 'estates@privateholdings.com',
    phone: '+1 (555) 234-5683',
    address: 'Confidential',
    contactPerson: 'Elizabeth Thompson',
    status: 'active',
    projects: 1,
    totalBudget: 650000,
    createdAt: '2023-12-01T09:00:00Z'
  },
  {
    id: 'client-7',
    name: 'Modern Living Developments',
    type: 'Residential Developer',
    email: 'info@modernliving.com',
    phone: '+1 (555) 234-5684',
    address: '3000 Skyline Tower',
    contactPerson: 'Michael Foster',
    status: 'active',
    projects: 1,
    totalBudget: 420000,
    createdAt: '2024-01-08T11:00:00Z'
  },
  {
    id: 'client-8',
    name: 'Heritage Restoration Society',
    type: 'Non-Profit',
    email: 'projects@heritagerestoration.org',
    phone: '+1 (555) 234-5685',
    address: '789 Heritage Hill Road',
    contactPerson: 'Sarah Williams',
    status: 'active',
    projects: 1,
    totalBudget: 880000,
    createdAt: '2024-02-15T10:00:00Z'
  },
  {
    id: 'client-9',
    name: 'City Arts Council',
    type: 'Government',
    email: 'facilities@cityarts.gov',
    phone: '+1 (555) 234-5686',
    address: '456 Culture Center, Arts District',
    contactPerson: 'Jennifer Park',
    status: 'active',
    projects: 1,
    totalBudget: 520000,
    createdAt: '2024-03-01T09:00:00Z'
  },
  {
    id: 'client-10',
    name: 'National Restaurant Group',
    type: 'Hospitality',
    email: 'construction@nationalrestaurants.com',
    phone: '+1 (555) 234-5687',
    address: '123 Franchise Way, Business Park',
    contactPerson: 'Anthony Garcia',
    status: 'active',
    projects: 1,
    totalBudget: 380000,
    createdAt: '2024-01-20T08:00:00Z'
  }
];

// Shop Drawings
export const demoShopDrawings = [
  {
    id: 'sd-1',
    projectId: 'proj-1',
    name: 'Storefront Details - Section A',
    description: 'Detailed drawings for luxury retail storefronts',
    fileType: 'pdf',
    version: '2.0',
    status: 'approved',
    submittedBy: 'team-13',
    submittedDate: '2024-06-15T10:00:00Z',
    approvedBy: 'team-1',
    approvedDate: '2024-06-18T14:00:00Z',
    fileSize: '4.2 MB',
    pages: 8,
    tags: ['storefront', 'retail', 'section'],
    revisions: 2
  },
  {
    id: 'sd-2',
    projectId: 'proj-1',
    name: 'Kiosk Assembly Drawing',
    description: 'Assembly instructions for center court kiosks',
    fileType: 'pdf',
    version: '1.0',
    status: 'pending',
    submittedBy: 'team-14',
    submittedDate: '2024-06-25T11:00:00Z',
    fileSize: '2.8 MB',
    pages: 5,
    tags: ['kiosk', 'assembly'],
    revisions: 0
  },
  {
    id: 'sd-3',
    projectId: 'proj-2',
    name: 'Workstation Layout Plan',
    description: 'Modular workstation configuration and dimensions',
    fileType: 'dwg',
    version: '3.0',
    status: 'approved',
    submittedBy: 'team-13',
    submittedDate: '2024-05-20T09:00:00Z',
    approvedBy: 'team-2',
    approvedDate: '2024-05-22T16:00:00Z',
    fileSize: '1.5 MB',
    pages: 3,
    tags: ['workstation', 'layout'],
    revisions: 3
  },
  {
    id: 'sd-4',
    projectId: 'proj-3',
    name: 'Nurse Station Elevations',
    description: 'Front and side elevations for nurse stations',
    fileType: 'pdf',
    version: '1.5',
    status: 'in-review',
    submittedBy: 'team-14',
    submittedDate: '2024-06-28T14:00:00Z',
    fileSize: '3.1 MB',
    pages: 6,
    tags: ['medical', 'nurse-station', 'elevation'],
    revisions: 1,
    comments: ['Verify ADA compliance on counter heights']
  },
  {
    id: 'sd-5',
    projectId: 'proj-4',
    name: 'Reception Desk Details',
    description: 'Curved reception desk with onyx panels',
    fileType: 'pdf',
    version: '2.0',
    status: 'approved',
    submittedBy: 'team-13',
    submittedDate: '2024-06-10T10:00:00Z',
    approvedBy: 'team-1',
    approvedDate: '2024-06-12T15:00:00Z',
    fileSize: '5.7 MB',
    pages: 10,
    tags: ['reception', 'hotel', 'luxury'],
    revisions: 2
  },
  {
    id: 'sd-6',
    projectId: 'proj-5',
    name: 'Boardroom Table Construction',
    description: '30-foot boardroom table with integrated technology',
    fileType: 'pdf',
    version: '1.0',
    status: 'pending',
    submittedBy: 'team-14',
    submittedDate: '2024-06-30T09:00:00Z',
    fileSize: '4.5 MB',
    pages: 12,
    tags: ['boardroom', 'executive', 'technology'],
    revisions: 0
  },
  {
    id: 'sd-7',
    projectId: 'proj-6',
    name: 'Wine Cellar Racking System',
    description: 'Climate-controlled wine storage details',
    fileType: 'dwg',
    version: '1.0',
    status: 'approved',
    submittedBy: 'team-13',
    submittedDate: '2024-06-20T11:00:00Z',
    approvedBy: 'team-2',
    approvedDate: '2024-06-22T14:00:00Z',
    fileSize: '2.3 MB',
    pages: 4,
    tags: ['wine-cellar', 'residential', 'storage'],
    revisions: 0
  },
  {
    id: 'sd-8',
    projectId: 'proj-9',
    name: 'Display Case Specifications',
    description: 'Museum-quality display cases with security',
    fileType: 'pdf',
    version: '1.0',
    status: 'in-review',
    submittedBy: 'team-14',
    submittedDate: '2024-06-29T10:00:00Z',
    fileSize: '3.8 MB',
    pages: 7,
    tags: ['museum', 'display', 'security'],
    revisions: 0,
    comments: ['Confirm UV protection specifications']
  }
];

// Project Scopes
export const demoProjectScopes = [
  // Westfield Shopping Center Renovation - 18 items across all categories
  {
    projectId: 'proj-1',
    items: [
      // Construction Category
      { 
        id: 'scope-wsc-c001', 
        itemCode: 'WSC-C001',
        name: 'Foundation Work',
        description: 'Concrete foundation and structural support for storefront installations', 
        category: 'construction',
        quantity: 15, 
        unitPrice: 8500, 
        totalPrice: 127500,
        initialCost: 125000,
        actualCost: 127500,
        linkedDrawings: ['sd-1'],
        linkedSpecs: ['spec-1'],
        createdAt: '2024-01-15T10:00:00Z'
      },
      { 
        id: 'scope-wsc-c002', 
        itemCode: 'WSC-C002',
        name: 'Flooring Installation',
        description: 'Premium tile and hardwood flooring throughout shopping areas', 
        category: 'construction',
        quantity: 2500, 
        unitPrice: 85, 
        totalPrice: 212500,
        initialCost: 200000,
        actualCost: 212500,
        linkedDrawings: [],
        linkedSpecs: ['spec-1'],
        createdAt: '2024-01-16T09:00:00Z'
      },
      { 
        id: 'scope-wsc-c003', 
        itemCode: 'WSC-C003',
        name: 'Ceiling Systems',
        description: 'Suspended ceiling grid and acoustic panels', 
        category: 'construction',
        quantity: 3200, 
        unitPrice: 45, 
        totalPrice: 144000,
        initialCost: 150000,
        actualCost: 144000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-17T11:00:00Z'
      },
      { 
        id: 'scope-wsc-c004', 
        itemCode: 'WSC-C004',
        name: 'Glass Partitions',
        description: 'Tempered glass storefront partitions and doors', 
        category: 'construction',
        quantity: 25, 
        unitPrice: 3200, 
        totalPrice: 80000,
        initialCost: 75000,
        actualCost: 80000,
        linkedDrawings: ['sd-1'],
        linkedSpecs: ['spec-1'],
        createdAt: '2024-01-18T14:00:00Z'
      },

      // Millwork Category
      { 
        id: 'scope-wsc-m001', 
        itemCode: 'WSC-M001',
        name: 'Luxury Storefront Systems',
        description: 'Custom millwork for high-end retail storefronts with integrated lighting', 
        category: 'millwork',
        quantity: 15, 
        unitPrice: 45000, 
        totalPrice: 675000,
        initialCost: 650000,
        actualCost: 675000,
        linkedDrawings: ['sd-1'],
        linkedSpecs: ['spec-1'],
        createdAt: '2024-01-20T10:00:00Z'
      },
      { 
        id: 'scope-wsc-m002', 
        itemCode: 'WSC-M002',
        name: 'Center Court Kiosks',
        description: 'Handcrafted kiosks with premium finishes and storage', 
        category: 'millwork',
        quantity: 4, 
        unitPrice: 25000, 
        totalPrice: 100000,
        initialCost: 95000,
        actualCost: 100000,
        linkedDrawings: ['sd-2'],
        linkedSpecs: [],
        createdAt: '2024-01-21T11:00:00Z'
      },
      { 
        id: 'scope-wsc-m003', 
        itemCode: 'WSC-M003',
        name: 'Food Court Package',
        description: 'Complete millwork package for food court vendor spaces', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 180000, 
        totalPrice: 180000,
        initialCost: 175000,
        actualCost: 180000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-22T09:00:00Z'
      },
      { 
        id: 'scope-wsc-m004', 
        itemCode: 'WSC-M004',
        name: 'Directory Displays',
        description: 'Digital mall directory housing with premium wood finishes', 
        category: 'millwork',
        quantity: 6, 
        unitPrice: 8000, 
        totalPrice: 48000,
        initialCost: 50000,
        actualCost: 48000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-23T13:00:00Z'
      },
      { 
        id: 'scope-wsc-m005', 
        itemCode: 'WSC-M005',
        name: 'Service Desk Stations',
        description: 'Customer service and information desk stations', 
        category: 'millwork',
        quantity: 3, 
        unitPrice: 15000, 
        totalPrice: 45000,
        initialCost: 42000,
        actualCost: 45000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-24T15:00:00Z'
      },

      // Electrical Category
      { 
        id: 'scope-wsc-e001', 
        itemCode: 'WSC-E001',
        name: 'LED Lighting System',
        description: 'Energy-efficient LED lighting throughout shopping center', 
        category: 'electrical',
        quantity: 150, 
        unitPrice: 420, 
        totalPrice: 63000,
        initialCost: 65000,
        actualCost: 63000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-25T10:00:00Z'
      },
      { 
        id: 'scope-wsc-e002', 
        itemCode: 'WSC-E002',
        name: 'Power Distribution',
        description: 'Electrical distribution panels and wiring for storefronts', 
        category: 'electrical',
        quantity: 15, 
        unitPrice: 2800, 
        totalPrice: 42000,
        initialCost: 40000,
        actualCost: 42000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-26T11:00:00Z'
      },
      { 
        id: 'scope-wsc-e003', 
        itemCode: 'WSC-E003',
        name: 'Security Systems',
        description: 'CCTV cameras and access control systems', 
        category: 'electrical',
        quantity: 45, 
        unitPrice: 850, 
        totalPrice: 38250,
        initialCost: 35000,
        actualCost: 38250,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-27T12:00:00Z'
      },

      // Mechanical Category
      { 
        id: 'scope-wsc-mc001', 
        itemCode: 'WSC-MC001',
        name: 'HVAC Ductwork',
        description: 'Air conditioning ductwork and ventilation systems', 
        category: 'mechanical',
        quantity: 2500, 
        unitPrice: 35, 
        totalPrice: 87500,
        initialCost: 85000,
        actualCost: 87500,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-28T09:00:00Z'
      },
      { 
        id: 'scope-wsc-mc002', 
        itemCode: 'WSC-MC002',
        name: 'Air Handling Units',
        description: 'Commercial air handling units for climate control', 
        category: 'mechanical',
        quantity: 8, 
        unitPrice: 12500, 
        totalPrice: 100000,
        initialCost: 95000,
        actualCost: 100000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-29T14:00:00Z'
      },
      { 
        id: 'scope-wsc-mc003', 
        itemCode: 'WSC-MC003',
        name: 'Fire Suppression',
        description: 'Sprinkler system installation and safety equipment', 
        category: 'mechanical',
        quantity: 1, 
        unitPrice: 75000, 
        totalPrice: 75000,
        initialCost: 70000,
        actualCost: 75000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-30T16:00:00Z'
      }
    ]
  },

  // Tech Campus Office Buildout - 14 items focused on modern office
  {
    projectId: 'proj-2',
    items: [
      // Construction Category
      { 
        id: 'scope-tcp-c001', 
        itemCode: 'TCP-C001',
        name: 'Office Partitions',
        description: 'Glass and drywall partitions for open office layout', 
        category: 'construction',
        quantity: 25, 
        unitPrice: 1200, 
        totalPrice: 30000,
        initialCost: 28000,
        actualCost: 30000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-02-20T10:00:00Z'
      },
      { 
        id: 'scope-tcp-c002', 
        itemCode: 'TCP-C002',
        name: 'Raised Flooring',
        description: 'Access floor system for cable management', 
        category: 'construction',
        quantity: 1200, 
        unitPrice: 45, 
        totalPrice: 54000,
        initialCost: 50000,
        actualCost: 54000,
        linkedDrawings: [],
        linkedSpecs: ['spec-2'],
        createdAt: '2024-02-21T09:00:00Z'
      },

      // Millwork Category (Primary focus)
      { 
        id: 'scope-tcp-m001', 
        itemCode: 'TCP-M001',
        name: 'Open Office Workstations',
        description: 'Modern workstation pods with integrated storage', 
        category: 'millwork',
        quantity: 50, 
        unitPrice: 3500, 
        totalPrice: 175000,
        initialCost: 170000,
        actualCost: 175000,
        linkedDrawings: ['sd-3'],
        linkedSpecs: [],
        createdAt: '2024-02-22T11:00:00Z'
      },
      { 
        id: 'scope-tcp-m002', 
        itemCode: 'TCP-M002',
        name: 'Executive Conference Room',
        description: 'Premium conference table and built-in AV cabinetry', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 85000, 
        totalPrice: 85000,
        initialCost: 80000,
        actualCost: 85000,
        linkedDrawings: ['sd-3'],
        linkedSpecs: [],
        createdAt: '2024-02-23T13:00:00Z'
      },
      { 
        id: 'scope-tcp-m003', 
        itemCode: 'TCP-M003',
        name: 'Phone Booths',
        description: 'Acoustic phone booth pods for private calls', 
        category: 'millwork',
        quantity: 8, 
        unitPrice: 12000, 
        totalPrice: 96000,
        initialCost: 90000,
        actualCost: 96000,
        linkedDrawings: [],
        linkedSpecs: ['spec-2'],
        createdAt: '2024-02-24T14:00:00Z'
      },
      { 
        id: 'scope-tcp-m004', 
        itemCode: 'TCP-M004',
        name: 'Collaboration Pods',
        description: 'Casual meeting spaces with integrated technology', 
        category: 'millwork',
        quantity: 6, 
        unitPrice: 18000, 
        totalPrice: 108000,
        initialCost: 105000,
        actualCost: 108000,
        linkedDrawings: ['sd-3'],
        linkedSpecs: [],
        createdAt: '2024-02-25T15:00:00Z'
      },
      { 
        id: 'scope-tcp-m005', 
        itemCode: 'TCP-M005',
        name: 'Reception Desk',
        description: 'Modern reception desk with visitor management system housing', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 25000, 
        totalPrice: 25000,
        initialCost: 22000,
        actualCost: 25000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-02-26T10:00:00Z'
      },
      { 
        id: 'scope-tcp-m006', 
        itemCode: 'TCP-M006',
        name: 'Kitchen Cabinetry',
        description: 'Break room and kitchenette cabinetry with appliance housing', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 35000, 
        totalPrice: 35000,
        initialCost: 32000,
        actualCost: 35000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-02-27T12:00:00Z'
      },

      // Electrical Category
      { 
        id: 'scope-tcp-e001', 
        itemCode: 'TCP-E001',
        name: 'Smart Lighting',
        description: 'Automated LED lighting with occupancy sensors', 
        category: 'electrical',
        quantity: 80, 
        unitPrice: 320, 
        totalPrice: 25600,
        initialCost: 24000,
        actualCost: 25600,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-02-28T11:00:00Z'
      },
      { 
        id: 'scope-tcp-e002', 
        itemCode: 'TCP-E002',
        name: 'Data Infrastructure',
        description: 'Network cabling and data outlets for workstations', 
        category: 'electrical',
        quantity: 60, 
        unitPrice: 180, 
        totalPrice: 10800,
        initialCost: 12000,
        actualCost: 10800,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-03-01T09:00:00Z'
      },

      // Mechanical Category
      { 
        id: 'scope-tcp-mc001', 
        itemCode: 'TCP-MC001',
        name: 'Zone Control HVAC',
        description: 'Individual zone climate control for flexible workspace', 
        category: 'mechanical',
        quantity: 12, 
        unitPrice: 4500, 
        totalPrice: 54000,
        initialCost: 50000,
        actualCost: 54000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-03-02T10:00:00Z'
      },
      { 
        id: 'scope-tcp-mc002', 
        itemCode: 'TCP-MC002',
        name: 'Air Quality Systems',
        description: 'Advanced air filtration and monitoring systems', 
        category: 'mechanical',
        quantity: 6, 
        unitPrice: 6800, 
        totalPrice: 40800,
        initialCost: 38000,
        actualCost: 40800,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-03-03T14:00:00Z'
      }
    ]
  },

  // Medical Plaza Construction - 20 items with medical-specific requirements
  {
    projectId: 'proj-3',
    items: [
      // Construction Category
      { 
        id: 'scope-mpc-c001', 
        itemCode: 'MPC-C001',
        name: 'Medical Grade Flooring',
        description: 'Non-slip, antimicrobial flooring for patient areas', 
        category: 'construction',
        quantity: 1800, 
        unitPrice: 95, 
        totalPrice: 171000,
        initialCost: 165000,
        actualCost: 171000,
        linkedDrawings: [],
        linkedSpecs: ['spec-3'],
        createdAt: '2024-01-25T10:00:00Z'
      },
      { 
        id: 'scope-mpc-c002', 
        itemCode: 'MPC-C002',
        name: 'Lead-Lined Walls',
        description: 'X-ray room shielding and protective barriers', 
        category: 'construction',
        quantity: 8, 
        unitPrice: 12500, 
        totalPrice: 100000,
        initialCost: 95000,
        actualCost: 100000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-26T11:00:00Z'
      },
      { 
        id: 'scope-mpc-c003', 
        itemCode: 'MPC-C003',
        name: 'Clean Room Construction',
        description: 'Sterile environment construction for surgical suites', 
        category: 'construction',
        quantity: 4, 
        unitPrice: 45000, 
        totalPrice: 180000,
        initialCost: 175000,
        actualCost: 180000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-27T09:00:00Z'
      },

      // Millwork Category (Medical Casework)
      { 
        id: 'scope-mpc-m001', 
        itemCode: 'MPC-M001',
        name: 'Nurse Stations - Type A',
        description: 'Central nurse stations with medication storage and charting areas', 
        category: 'millwork',
        quantity: 8, 
        unitPrice: 35000, 
        totalPrice: 280000,
        initialCost: 275000,
        actualCost: 280000,
        linkedDrawings: ['sd-4'],
        linkedSpecs: ['spec-3'],
        createdAt: '2024-01-28T10:00:00Z'
      },
      { 
        id: 'scope-mpc-m002', 
        itemCode: 'MPC-M002',
        name: 'Nurse Stations - Type B',
        description: 'Satellite nurse stations for wing coverage', 
        category: 'millwork',
        quantity: 4, 
        unitPrice: 28000, 
        totalPrice: 112000,
        initialCost: 110000,
        actualCost: 112000,
        linkedDrawings: ['sd-4'],
        linkedSpecs: ['spec-3'],
        createdAt: '2024-01-29T11:00:00Z'
      },
      { 
        id: 'scope-mpc-m003', 
        itemCode: 'MPC-M003',
        name: 'Patient Room Casework',
        description: 'Bedside casework with medical gas outlets and storage', 
        category: 'millwork',
        quantity: 50, 
        unitPrice: 4500, 
        totalPrice: 225000,
        initialCost: 220000,
        actualCost: 225000,
        linkedDrawings: [],
        linkedSpecs: ['spec-3'],
        createdAt: '2024-01-30T12:00:00Z'
      },
      { 
        id: 'scope-mpc-m004', 
        itemCode: 'MPC-M004',
        name: 'Pharmacy Millwork',
        description: 'Secure pharmaceutical storage and dispensing stations', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 125000, 
        totalPrice: 125000,
        initialCost: 120000,
        actualCost: 125000,
        linkedDrawings: [],
        linkedSpecs: ['spec-3'],
        createdAt: '2024-02-01T13:00:00Z'
      },
      { 
        id: 'scope-mpc-m005', 
        itemCode: 'MPC-M005',
        name: 'Laboratory Casework',
        description: 'Chemical-resistant lab benches and fume hoods', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 185000, 
        totalPrice: 185000,
        initialCost: 180000,
        actualCost: 185000,
        linkedDrawings: [],
        linkedSpecs: ['spec-3'],
        createdAt: '2024-02-02T14:00:00Z'
      },
      { 
        id: 'scope-mpc-m006', 
        itemCode: 'MPC-M006',
        name: 'Reception Desk',
        description: 'Patient check-in desk with privacy screens', 
        category: 'millwork',
        quantity: 3, 
        unitPrice: 18000, 
        totalPrice: 54000,
        initialCost: 52000,
        actualCost: 54000,
        createdAt: '2024-02-03T15:00:00Z'
      },

      // Electrical Category
      { 
        id: 'scope-mpc-e001', 
        itemCode: 'MPC-E001',
        name: 'Medical Equipment Power',
        description: 'Isolated power systems for medical equipment', 
        category: 'electrical',
        quantity: 25, 
        unitPrice: 2400, 
        totalPrice: 60000,
        initialCost: 58000,
        actualCost: 60000,
        createdAt: '2024-02-04T10:00:00Z'
      },
      { 
        id: 'scope-mpc-e002', 
        itemCode: 'MPC-E002',
        name: 'Emergency Lighting',
        description: 'Battery backup lighting for emergency procedures', 
        category: 'electrical',
        quantity: 40, 
        unitPrice: 450, 
        totalPrice: 18000,
        initialCost: 17000,
        actualCost: 18000,
        createdAt: '2024-02-05T11:00:00Z'
      },
      { 
        id: 'scope-mpc-e003', 
        itemCode: 'MPC-E003',
        name: 'Nurse Call Systems',
        description: 'Patient communication and emergency alert systems', 
        category: 'electrical',
        quantity: 50, 
        unitPrice: 680, 
        totalPrice: 34000,
        initialCost: 32000,
        actualCost: 34000,
        createdAt: '2024-02-06T12:00:00Z'
      },

      // Mechanical Category
      { 
        id: 'scope-mpc-mc001', 
        itemCode: 'MPC-MC001',
        name: 'Medical Gas Systems',
        description: 'Oxygen, nitrogen, and vacuum gas distribution', 
        category: 'mechanical',
        quantity: 1, 
        unitPrice: 150000, 
        totalPrice: 150000,
        initialCost: 145000,
        actualCost: 150000,
        createdAt: '2024-02-07T13:00:00Z'
      },
      { 
        id: 'scope-mpc-mc002', 
        itemCode: 'MPC-MC002',
        name: 'HVAC Air Filtration',
        description: 'HEPA filtration systems for sterile environments', 
        category: 'mechanical',
        quantity: 12, 
        unitPrice: 8500, 
        totalPrice: 102000,
        initialCost: 100000,
        actualCost: 102000,
        createdAt: '2024-02-08T14:00:00Z'
      },
      { 
        id: 'scope-mpc-mc003', 
        itemCode: 'MPC-MC003',
        name: 'Steam Sterilization',
        description: 'Autoclave steam supply and condensate return', 
        category: 'mechanical',
        quantity: 6, 
        unitPrice: 12000, 
        totalPrice: 72000,
        initialCost: 70000,
        actualCost: 72000,
        createdAt: '2024-02-09T15:00:00Z'
      }
    ]
  },

  // Downtown Hotel Lobby Renovation - 12 items focused on luxury finishes
  {
    projectId: 'proj-4',
    items: [
      // Construction Category
      { 
        id: 'scope-dhl-c001', 
        itemCode: 'DHL-C001',
        name: 'Marble Flooring',
        description: 'Italian Carrara marble flooring installation', 
        category: 'construction',
        quantity: 800, 
        unitPrice: 185, 
        totalPrice: 148000,
        initialCost: 145000,
        actualCost: 148000,
        createdAt: '2024-03-05T10:00:00Z'
      },
      { 
        id: 'scope-dhl-c002', 
        itemCode: 'DHL-C002',
        name: 'Decorative Columns',
        description: 'Ornate column wrapping with luxury finishes', 
        category: 'construction',
        quantity: 8, 
        unitPrice: 8500, 
        totalPrice: 68000,
        initialCost: 65000,
        actualCost: 68000,
        createdAt: '2024-03-06T11:00:00Z'
      },

      // Millwork Category (Primary focus for hotel)
      { 
        id: 'scope-dhl-m001', 
        itemCode: 'DHL-M001',
        name: 'Reception Desk',
        description: 'Grand mahogany reception desk with gold leaf accents', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 95000, 
        totalPrice: 95000,
        initialCost: 90000,
        actualCost: 95000,
        linkedDrawings: ['sd-5'],
        linkedSpecs: ['spec-4'],
        createdAt: '2024-03-07T12:00:00Z'
      },
      { 
        id: 'scope-dhl-m002', 
        itemCode: 'DHL-M002',
        name: 'Concierge Stations',
        description: 'Luxury concierge service counters with leather inlays', 
        category: 'millwork',
        quantity: 2, 
        unitPrice: 28000, 
        totalPrice: 56000,
        initialCost: 55000,
        actualCost: 56000,
        linkedDrawings: ['sd-5'],
        linkedSpecs: [],
        createdAt: '2024-03-08T13:00:00Z'
      },
      { 
        id: 'scope-dhl-m003', 
        itemCode: 'DHL-M003',
        name: 'Decorative Wall Panels',
        description: 'Hand-carved walnut wall paneling with artistic details', 
        category: 'millwork',
        quantity: 12, 
        unitPrice: 15000, 
        totalPrice: 180000,
        initialCost: 175000,
        actualCost: 180000,
        createdAt: '2024-03-09T14:00:00Z'
      },
      { 
        id: 'scope-dhl-m004', 
        itemCode: 'DHL-M004',
        name: 'Lounge Seating Built-ins',
        description: 'Custom seating areas with integrated storage', 
        category: 'millwork',
        quantity: 6, 
        unitPrice: 22000, 
        totalPrice: 132000,
        initialCost: 128000,
        actualCost: 132000,
        createdAt: '2024-03-10T15:00:00Z'
      },

      // Electrical Category
      { 
        id: 'scope-dhl-e001', 
        itemCode: 'DHL-E001',
        name: 'Chandelier Installation',
        description: 'Crystal chandelier electrical and mounting systems', 
        category: 'electrical',
        quantity: 3, 
        unitPrice: 8500, 
        totalPrice: 25500,
        initialCost: 24000,
        actualCost: 25500,
        createdAt: '2024-03-11T10:00:00Z'
      },
      { 
        id: 'scope-dhl-e002', 
        itemCode: 'DHL-E002',
        name: 'Accent Lighting',
        description: 'LED accent lighting for architectural features', 
        category: 'electrical',
        quantity: 45, 
        unitPrice: 380, 
        totalPrice: 17100,
        initialCost: 16000,
        actualCost: 17100,
        createdAt: '2024-03-12T11:00:00Z'
      },

      // Mechanical Category
      { 
        id: 'scope-dhl-mc001', 
        itemCode: 'DHL-MC001',
        name: 'Climate Control',
        description: 'Precision HVAC for guest comfort in lobby areas', 
        category: 'mechanical',
        quantity: 4, 
        unitPrice: 18500, 
        totalPrice: 74000,
        initialCost: 72000,
        actualCost: 74000,
        createdAt: '2024-03-13T12:00:00Z'
      },
      { 
        id: 'scope-dhl-mc002', 
        itemCode: 'DHL-MC002',
        name: 'Sound Systems',
        description: 'Background music and public address systems', 
        category: 'mechanical',
        quantity: 1, 
        unitPrice: 35000, 
        totalPrice: 35000,
        initialCost: 32000,
        actualCost: 35000,
        createdAt: '2024-03-14T13:00:00Z'
      }
    ]
  },

  // Corporate Headquarters Expansion - 16 items for executive spaces
  {
    projectId: 'proj-5',
    items: [
      // Construction Category
      { 
        id: 'scope-che-c001', 
        itemCode: 'CHE-C001',
        name: 'Executive Floor Build-out',
        description: 'Premium construction for C-suite executive floor', 
        category: 'construction',
        quantity: 1, 
        unitPrice: 285000, 
        totalPrice: 285000,
        initialCost: 275000,
        actualCost: 285000,
        createdAt: '2024-01-15T10:00:00Z'
      },
      { 
        id: 'scope-che-c002', 
        itemCode: 'CHE-C002',
        name: 'Soundproof Partitions',
        description: 'Acoustic partitions for executive privacy', 
        category: 'construction',
        quantity: 15, 
        unitPrice: 3200, 
        totalPrice: 48000,
        initialCost: 45000,
        actualCost: 48000,
        createdAt: '2024-01-16T11:00:00Z'
      },

      // Millwork Category (Primary focus)
      { 
        id: 'scope-che-m001', 
        itemCode: 'CHE-M001',
        name: 'Boardroom Table',
        description: '30-foot custom boardroom table with integrated technology wells', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 120000, 
        totalPrice: 120000,
        initialCost: 115000,
        actualCost: 120000,
        linkedDrawings: ['sd-6'],
        linkedSpecs: ['spec-5'],
        createdAt: '2024-01-17T12:00:00Z'
      },
      { 
        id: 'scope-che-m002', 
        itemCode: 'CHE-M002',
        name: 'Executive Office Suites',
        description: 'Custom millwork for 10 executive offices with built-in storage', 
        category: 'millwork',
        quantity: 10, 
        unitPrice: 45000, 
        totalPrice: 450000,
        initialCost: 440000,
        actualCost: 450000,
        linkedDrawings: ['sd-6'],
        linkedSpecs: ['spec-5'],
        createdAt: '2024-01-18T13:00:00Z'
      },
      { 
        id: 'scope-che-m003', 
        itemCode: 'CHE-M003',
        name: 'Reception Area Millwork',
        description: 'Grand reception desk and waiting area furniture', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 95000, 
        totalPrice: 95000,
        initialCost: 90000,
        actualCost: 95000,
        linkedDrawings: [],
        linkedSpecs: [],
        createdAt: '2024-01-19T14:00:00Z'
      },
      { 
        id: 'scope-che-m004', 
        itemCode: 'CHE-M004',
        name: 'Break Room Cabinetry',
        description: 'Executive break room cabinetry with premium appliances housing', 
        category: 'millwork',
        quantity: 2, 
        unitPrice: 25000, 
        totalPrice: 50000,
        initialCost: 48000,
        actualCost: 50000,
        createdAt: '2024-01-20T15:00:00Z'
      },
      { 
        id: 'scope-che-m005', 
        itemCode: 'CHE-M005',
        name: 'Library Shelving',
        description: 'Executive library with custom book shelving and reading areas', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 85000, 
        totalPrice: 85000,
        initialCost: 80000,
        actualCost: 85000,
        createdAt: '2024-01-21T10:00:00Z'
      },
      { 
        id: 'scope-che-m006', 
        itemCode: 'CHE-M006',
        name: 'Storage Systems',
        description: 'Built-in storage solutions throughout executive areas', 
        category: 'millwork',
        quantity: 1, 
        unitPrice: 60000, 
        totalPrice: 60000,
        initialCost: 58000,
        actualCost: 60000,
        createdAt: '2024-01-22T11:00:00Z'
      },

      // Electrical Category
      { 
        id: 'scope-che-e001', 
        itemCode: 'CHE-E001',
        name: 'Premium Lighting',
        description: 'High-end lighting fixtures for executive spaces', 
        category: 'electrical',
        quantity: 35, 
        unitPrice: 1200, 
        totalPrice: 42000,
        initialCost: 40000,
        actualCost: 42000,
        createdAt: '2024-01-23T12:00:00Z'
      },
      { 
        id: 'scope-che-e002', 
        itemCode: 'CHE-E002',
        name: 'AV Integration',
        description: 'Audio-visual systems for boardroom and offices', 
        category: 'electrical',
        quantity: 12, 
        unitPrice: 4500, 
        totalPrice: 54000,
        initialCost: 50000,
        actualCost: 54000,
        createdAt: '2024-01-24T13:00:00Z'
      },
      { 
        id: 'scope-che-e003', 
        itemCode: 'CHE-E003',
        name: 'Security Access',
        description: 'Card access and biometric security systems', 
        category: 'electrical',
        quantity: 8, 
        unitPrice: 2800, 
        totalPrice: 22400,
        initialCost: 20000,
        actualCost: 22400,
        createdAt: '2024-01-25T14:00:00Z'
      },

      // Mechanical Category
      { 
        id: 'scope-che-mc001', 
        itemCode: 'CHE-MC001',
        name: 'Executive HVAC',
        description: 'Individual climate control for each executive office', 
        category: 'mechanical',
        quantity: 12, 
        unitPrice: 6500, 
        totalPrice: 78000,
        initialCost: 75000,
        actualCost: 78000,
        createdAt: '2024-01-26T15:00:00Z'
      },
      { 
        id: 'scope-che-mc002', 
        itemCode: 'CHE-MC002',
        name: 'Air Purification',
        description: 'Premium air filtration and purification systems', 
        category: 'mechanical',
        quantity: 6, 
        unitPrice: 8500, 
        totalPrice: 51000,
        initialCost: 48000,
        actualCost: 51000,
        createdAt: '2024-01-27T10:00:00Z'
      }
    ]
  }
];

// Activity Feed / Updates
export const demoActivities = [
  {
    id: 'activity-1',
    type: 'task_completed',
    title: 'Task Completed',
    description: 'Sarah Johnson completed "Storefront Design Approval"',
    projectId: 'proj-1',
    userId: 'team-1',
    timestamp: '2024-06-30T14:30:00Z',
    metadata: { taskId: 'task-1', taskName: 'Storefront Design Approval' }
  },
  {
    id: 'activity-2',
    type: 'drawing_approved',
    title: 'Shop Drawing Approved',
    description: 'Reception Desk Details drawing approved by Sarah Johnson',
    projectId: 'proj-4',
    userId: 'team-1',
    timestamp: '2024-06-30T13:45:00Z',
    metadata: { drawingId: 'sd-5', drawingName: 'Reception Desk Details' }
  },
  {
    id: 'activity-3',
    type: 'team_assigned',
    title: 'Team Member Assigned',
    description: 'Christopher Davis assigned to "Executive Conference Room" task',
    projectId: 'proj-2',
    userId: 'team-2',
    timestamp: '2024-06-30T11:20:00Z',
    metadata: { taskId: 'task-7', memberId: 'team-9' }
  },
  {
    id: 'activity-4',
    type: 'milestone_reached',
    title: 'Milestone Achieved',
    description: 'Tech Campus Office reached 80% completion',
    projectId: 'proj-2',
    userId: 'team-2',
    timestamp: '2024-06-30T10:00:00Z',
    metadata: { milestone: '80% Complete', progress: 82 }
  },
  {
    id: 'activity-5',
    type: 'material_delivered',
    title: 'Material Delivery',
    description: 'Premium walnut veneer delivered for Luxury Waterfront Estate',
    projectId: 'proj-6',
    userId: 'team-8',
    timestamp: '2024-06-30T09:15:00Z',
    metadata: { material: 'Walnut Veneer', quantity: '500 sq ft' }
  },
  {
    id: 'activity-6',
    type: 'drawing_submitted',
    title: 'Drawing Submitted',
    description: 'Boardroom Table Construction drawing submitted for review',
    projectId: 'proj-5',
    userId: 'team-14',
    timestamp: '2024-06-30T09:00:00Z',
    metadata: { drawingId: 'sd-6', version: '1.0' }
  },
  {
    id: 'activity-7',
    type: 'task_started',
    title: 'Task Started',
    description: 'Installation of Center Court Kiosks has begun',
    projectId: 'proj-1',
    userId: 'team-7',
    timestamp: '2024-06-29T16:00:00Z',
    metadata: { taskId: 'task-3' }
  },
  {
    id: 'activity-8',
    type: 'client_approval',
    title: 'Client Approval',
    description: 'Westfield Properties approved kiosk design modifications',
    projectId: 'proj-1',
    userId: 'team-1',
    timestamp: '2024-06-29T15:30:00Z',
    metadata: { clientId: 'client-1', approvalType: 'Design Change' }
  },
  {
    id: 'activity-9',
    type: 'quality_check',
    title: 'Quality Inspection',
    description: 'Patricia Walker completed quality inspection for workstation installation',
    projectId: 'proj-2',
    userId: 'team-18',
    timestamp: '2024-06-29T14:00:00Z',
    metadata: { result: 'Passed', checklist: 'QC-2024-047' }
  },
  {
    id: 'activity-10',
    type: 'safety_update',
    title: 'Safety Briefing',
    description: 'Richard Lewis conducted safety briefing for Medical Plaza team',
    projectId: 'proj-3',
    userId: 'team-17',
    timestamp: '2024-06-29T08:00:00Z',
    metadata: { attendees: 8, topics: ['PPE Requirements', 'Site Hazards'] }
  },
  {
    id: 'activity-11',
    type: 'project_update',
    title: 'Progress Update',
    description: 'Corporate Headquarters Expansion reached 55% completion',
    projectId: 'proj-5',
    userId: 'team-1',
    timestamp: '2024-06-28T17:00:00Z',
    metadata: { previousProgress: 50, newProgress: 55 }
  },
  {
    id: 'activity-12',
    type: 'photo_uploaded',
    title: 'Progress Photos',
    description: 'Michael Chen uploaded 12 progress photos for Tech Campus',
    projectId: 'proj-2',
    userId: 'team-2',
    timestamp: '2024-06-28T16:30:00Z',
    metadata: { photoCount: 12, location: 'Conference Room' }
  },
  {
    id: 'activity-13',
    type: 'scope_change',
    title: 'Scope Addition',
    description: 'Added custom lighting integration to Museum Gallery project',
    projectId: 'proj-9',
    userId: 'team-2',
    timestamp: '2024-06-28T14:00:00Z',
    metadata: { changeOrder: 'CO-009-01', value: 35000 }
  },
  {
    id: 'activity-14',
    type: 'team_meeting',
    title: 'Team Meeting',
    description: 'Weekly coordination meeting for Westfield Shopping Center',
    projectId: 'proj-1',
    userId: 'team-1',
    timestamp: '2024-06-28T10:00:00Z',
    metadata: { attendees: ['team-1', 'team-2', 'team-3', 'team-7', 'team-8'] }
  },
  {
    id: 'activity-15',
    type: 'invoice_submitted',
    title: 'Invoice Submitted',
    description: 'Progress billing submitted for Downtown Hotel Lobby',
    projectId: 'proj-4',
    userId: 'team-15',
    timestamp: '2024-06-27T16:00:00Z',
    metadata: { invoiceNumber: 'INV-2024-089', amount: 525000 }
  }
];

// Material Specifications
export const demoMaterialSpecs = [
  {
    id: 'spec-1',
    projectId: 'proj-1',
    projectName: 'Westfield Shopping Center Renovation',
    name: 'High-End Retail Storefront Glass',
    category: 'Glass & Glazing',
    description: 'Low-iron structural glazing for luxury retail storefronts with anti-reflective coating',
    specifications: 'Thickness: 12mm, Size: 2400x3600mm, Coating: Guardian ClimaGuard Premium',
    supplier: 'Guardian Glass LLC',
    unitCost: '$450.00',
    quantity: '150',
    unit: 'panels',
    totalCost: '$67,500.00',
    leadTime: '6-8 weeks',
    status: 'approved',
    approvedBy: 'team-1',
    approvedDate: '2024-06-15T10:00:00Z',
    linkedDrawings: ['sd-1'],
    linkedTasks: ['task-1'],
    notes: 'Certified for hurricane impact resistance',
    submittedDate: '2024-06-01T09:00:00Z',
    lastModified: '2024-06-15T10:00:00Z'
  },
  {
    id: 'spec-2',
    projectId: 'proj-2',
    projectName: 'Tech Campus Office Buildout',
    name: 'Acoustical Ceiling Panels',
    category: 'Ceilings',
    description: 'High-performance acoustic ceiling panels for open office environment',
    specifications: 'Armstrong Ultima Vector, NRC 0.85, Size: 24"x48"x5/8"',
    supplier: 'Armstrong Ceiling Solutions',
    unitCost: '$24.50',
    quantity: '800',
    unit: 'panels',
    totalCost: '$19,600.00',
    leadTime: '3-4 weeks',
    status: 'pending',
    linkedDrawings: ['sd-2'],
    linkedTasks: ['task-7'],
    notes: 'Requires seismic hold-down clips',
    submittedDate: '2024-06-20T14:00:00Z',
    lastModified: '2024-06-20T14:00:00Z'
  },
  {
    id: 'spec-3',
    projectId: 'proj-3',
    projectName: 'Medical Plaza Construction',
    name: 'Healthcare Grade Solid Surface',
    category: 'Surfaces',
    description: 'Non-porous solid surface material for medical casework and countertops',
    specifications: 'Corian Glacier White, 1/2" thickness, seamless integration',
    supplier: 'DuPont Building Solutions',
    unitCost: '$85.00',
    quantity: '2,400',
    unit: 'sq ft',
    totalCost: '$204,000.00',
    leadTime: '4-6 weeks',
    status: 'in-review',
    linkedDrawings: ['sd-7'],
    linkedTasks: ['task-10'],
    notes: 'Antimicrobial properties required for healthcare application',
    submittedDate: '2024-06-18T11:30:00Z',
    lastModified: '2024-06-25T16:00:00Z'
  },
  {
    id: 'spec-4',
    projectId: 'proj-4',
    projectName: 'Downtown Hotel Lobby Renovation',
    name: 'Premium Natural Stone',
    category: 'Stone',
    description: 'Book-matched Calacatta marble for reception desk and feature walls',
    specifications: 'Calacatta Gold, 20mm slabs, book-matched veining, honed finish',
    supplier: 'Stone Source International',
    unitCost: '$180.00',
    quantity: '450',
    unit: 'sq ft',
    totalCost: '$81,000.00',
    leadTime: '8-10 weeks',
    status: 'approved',
    approvedBy: 'team-1',
    approvedDate: '2024-06-10T14:30:00Z',
    linkedDrawings: ['sd-5'],
    linkedTasks: ['task-12'],
    notes: 'Requires structural verification for weight load',
    submittedDate: '2024-05-28T09:00:00Z',
    lastModified: '2024-06-10T14:30:00Z'
  },
  {
    id: 'spec-5',
    projectId: 'proj-5',
    projectName: 'Corporate Headquarters Expansion',
    name: 'Executive Grade Wood Veneer',
    category: 'Wood Products',
    description: 'Quartered cherry veneer for executive boardroom millwork',
    specifications: 'North American Cherry, quarter-sawn, plain sliced, 0.6mm thickness',
    supplier: 'Oakwood Veneer Company',
    unitCost: '$45.00',
    quantity: '800',
    unit: 'sq ft',
    totalCost: '$36,000.00',
    leadTime: '5-7 weeks',
    status: 'pending',
    linkedDrawings: ['sd-6'],
    linkedTasks: ['task-15'],
    notes: 'FSC certified sustainable harvesting required',
    submittedDate: '2024-06-22T10:15:00Z',
    lastModified: '2024-06-22T10:15:00Z'
  },
  {
    id: 'spec-6',
    projectId: 'proj-6',
    projectName: 'Luxury Waterfront Estate',
    name: 'Marine Grade Hardware',
    category: 'Hardware',
    description: 'Corrosion-resistant hardware for coastal environment millwork',
    specifications: 'Stainless Steel 316, satin finish, concealed hinges and slides',
    supplier: 'Hafele Marine Hardware',
    unitCost: '$125.00',
    quantity: '240',
    unit: 'sets',
    totalCost: '$30,000.00',
    leadTime: '6-8 weeks',
    status: 'revision-required',
    linkedDrawings: ['sd-4'],
    linkedTasks: ['task-18'],
    notes: 'Salt spray testing certification required',
    submittedDate: '2024-06-12T13:45:00Z',
    lastModified: '2024-06-28T09:30:00Z'
  },
  {
    id: 'spec-7',
    projectId: 'proj-7',
    projectName: 'Modern Art Gallery Renovation',
    name: 'Conservation Grade LED Lighting',
    category: 'Lighting',
    description: 'Museum-quality LED track lighting with UV filtering',
    specifications: 'Erco Optec 3000K, CRI 98, UV-free, dimming compatible',
    supplier: 'Erco Lighting Systems',
    unitCost: '$850.00',
    quantity: '45',
    unit: 'fixtures',
    totalCost: '$38,250.00',
    leadTime: '10-12 weeks',
    status: 'approved',
    approvedBy: 'team-2',
    approvedDate: '2024-06-20T11:00:00Z',
    linkedDrawings: ['sd-8'],
    linkedTasks: ['task-20'],
    notes: 'Must meet conservation lighting standards',
    submittedDate: '2024-06-05T16:20:00Z',
    lastModified: '2024-06-20T11:00:00Z'
  },
  {
    id: 'spec-8',
    projectId: 'proj-8',
    projectName: 'Boutique Fitness Studio',
    name: 'High-Performance Flooring',
    category: 'Flooring',
    description: 'Athletic performance flooring with shock absorption',
    specifications: 'Mondo SportsFlex, 8mm thickness, multi-sport surface',
    supplier: 'Mondo Sports Flooring',
    unitCost: '$28.50',
    quantity: '3,200',
    unit: 'sq ft',
    totalCost: '$91,200.00',
    leadTime: '4-5 weeks',
    status: 'pending',
    linkedDrawings: [],
    linkedTasks: ['task-21'],
    notes: 'Requires subfloor preparation specifications',
    submittedDate: '2024-06-25T08:30:00Z',
    lastModified: '2024-06-25T08:30:00Z'
  }
];

// My Work data (for the current user)
export const demoMyWork = {
  assignedTasks: [
    'task-3', 'task-7', 'task-14', 'task-16', 'task-19', 'task-22'
  ],
  managedProjects: [
    'proj-1', 'proj-4', 'proj-5', 'proj-8'
  ],
  recentActivities: [
    'activity-1', 'activity-2', 'activity-8', 'activity-11', 'activity-14'
  ],
  upcomingDeadlines: [
    { taskId: 'task-3', dueDate: '2024-07-15', daysUntil: 15 },
    { taskId: 'task-14', dueDate: '2024-07-20', daysUntil: 20 },
    { taskId: 'task-16', dueDate: '2024-08-01', daysUntil: 32 }
  ],
  stats: {
    tasksCompleted: 12,
    tasksInProgress: 6,
    projectsActive: 4,
    teamSize: 18
  }
};

// Helper function to get demo data
export const getDemoData = () => {
  return {
    projects: demoProjects,
    tasks: demoTasks,
    teamMembers: demoTeamMembers,
    clients: demoClients,
    shopDrawings: demoShopDrawings,
    projectScopes: demoProjectScopes,
    activities: demoActivities,
    materialSpecs: demoMaterialSpecs,
    myWork: demoMyWork
  };
};

// Helper to simulate API responses
export const simulateApiResponse = (data, delay = 300) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        success: true,
        data: data,
        message: 'Demo data loaded successfully'
      });
    }, delay);
  });
};

export default {
  demoProjects,
  demoTasks,
  demoTeamMembers,
  demoClients,
  demoShopDrawings,
  demoProjectScopes,
  demoActivities,
  demoMaterialSpecs,
  demoMyWork,
  getDemoData,
  simulateApiResponse
};