// Import the Formula International team data
const formulaEmployees = [
  {
    id: 1001,
    firstName: "Kubilay",
    lastName: "Ilgın",
    fullName: "Kubilay Ilgın",
    initials: "KI",
    email: "kubilay.ilgin@formulaint.com",
    phone: "+90 212 555 0101",
    username: "kubilay.ilgin",
    position: "Managing Partner",
    role: "super_admin",
    level: 10,
    department: "management",
    reportsTo: null,
    status: "active",
    permissions: ["all"],
    roleColor: "#8e44ad",
    hourlyRate: 250,
    notes: "Co-founder and Managing Partner of Formula International"
  },
  {
    id: 1002,
    firstName: "Ömer",
    lastName: "Onan",
    fullName: "Ömer Onan",
    initials: "ÖO",
    email: "omer.onan@formulaint.com",
    phone: "+90 212 555 0102",
    username: "omer.onan",
    position: "Managing Partner",
    role: "super_admin",
    level: 10,
    department: "management",
    reportsTo: null,
    status: "active",
    permissions: ["all"],
    roleColor: "#8e44ad",
    hourlyRate: 250,
    notes: "Co-founder and Managing Partner of Formula International"
  },
  {
    id: 1003,
    firstName: "Taylan",
    lastName: "Kaygusuz",
    fullName: "Taylan Kaygusuz",
    initials: "TK",
    email: "taylan.kaygusuz@formulaint.com",
    phone: "+90 212 555 0103",
    username: "taylan.kaygusuz",
    position: "General Manager",
    role: "project_manager",
    level: 9,
    department: "management",
    reportsTo: "1001,1002",
    status: "active",
    permissions: ["manage_projects", "manage_teams", "view_all", "manage_users"],
    roleColor: "#e74c3c",
    hourlyRate: 200,
    notes: "General Manager overseeing all operations"
  },
  {
    id: 1004,
    firstName: "Cevahir",
    lastName: "Sevimli",
    fullName: "Cevahir Sevimli",
    initials: "CS",
    email: "cevahir.sevimli@formulaint.com",
    phone: "+90 212 555 0104",
    username: "cevahir.sevimli",
    position: "Deputy General Manager",
    role: "project_manager",
    level: 8,
    department: "management",
    reportsTo: "1001,1002,1003",
    status: "active",
    permissions: ["manage_projects", "assign_tasks", "view_reports"],
    roleColor: "#e67e22",
    hourlyRate: 180,
    notes: "Deputy General Manager"
  },
  {
    id: 1005,
    firstName: "Yusuf",
    lastName: "Sağlam",
    fullName: "Yusuf Sağlam",
    initials: "YS",
    email: "yusuf.saglam@formulaint.com",
    phone: "+90 212 555 0105",
    username: "yusuf.saglam",
    position: "Deputy General Manager",
    role: "project_manager",
    level: 8,
    department: "management",
    reportsTo: "1001,1002,1003",
    status: "active",
    permissions: ["manage_projects", "assign_tasks", "view_reports"],
    roleColor: "#e67e22",
    hourlyRate: 180,
    notes: "Deputy General Manager"
  },
  {
    id: 1006,
    firstName: "İpek",
    lastName: "Gönenç",
    fullName: "İpek Gönenç",
    initials: "İG",
    email: "ipek.gonenc@formulaint.com",
    phone: "+90 212 555 0106",
    username: "ipek.gonenc",
    position: "Project Director",
    role: "project_manager",
    level: 7,
    department: "fit-out",
    reportsTo: "1001,1002,1003,1004",
    status: "active",
    permissions: ["manage_projects", "assign_tasks", "view_reports"],
    roleColor: "#e67e22",
    hourlyRate: 160,
    notes: "Project Director for Fit-out operations"
  },
  {
    id: 1007,
    firstName: "Berk",
    lastName: "Ulukan",
    fullName: "Berk Ulukan",
    initials: "BU",
    email: "berk.ulukan@formulaint.com",
    phone: "+90 212 555 0107",
    username: "berk.ulukan",
    position: "Director of Technical Office",
    role: "team_lead",
    level: 7,
    department: "mep",
    reportsTo: "1001,1002,1003,1004",
    status: "active",
    permissions: ["manage_team_tasks", "view_team_reports"],
    roleColor: "#f39c12",
    hourlyRate: 160,
    notes: "Director of Technical Office - MEP Department"
  },
  {
    id: 1008,
    firstName: "Kerem Salih",
    lastName: "Colak",
    fullName: "Kerem Salih Colak",
    initials: "KC",
    email: "kerem.colak@formulaint.com",
    phone: "+90 212 555 0108",
    username: "kerem.colak",
    position: "Project Manager",
    role: "project_manager",
    level: 6,
    department: "fit-out",
    reportsTo: "1001,1002,1003,1004",
    status: "active",
    permissions: ["manage_projects", "assign_tasks", "view_reports"],
    roleColor: "#e67e22",
    hourlyRate: 140,
    notes: "Project Manager - Fit-out Department",
    isCurrentUser: true
  },
  {
    id: 1009,
    firstName: "Hakan",
    lastName: "Ayseli",
    fullName: "Hakan Ayseli",
    initials: "HA",
    email: "hakan.ayseli@formulaint.com",
    phone: "+90 212 555 0109",
    username: "hakan.ayseli",
    position: "Project Manager/Site Manager",
    role: "project_manager",
    level: 6,
    department: "fit-out",
    reportsTo: "1001,1002,1003,1004",
    status: "active",
    permissions: ["manage_projects", "assign_tasks", "view_reports"],
    roleColor: "#e67e22",
    hourlyRate: 140,
    notes: "Project Manager and Site Manager"
  },
  {
    id: 1010,
    firstName: "Hande Selen",
    lastName: "Karaman",
    fullName: "Hande Selen Karaman",
    initials: "HK",
    email: "handeselen.karaman@formulaint.com",
    phone: "+90 212 555 0110",
    username: "handeselen.karaman",
    position: "Project Manager",
    role: "project_manager",
    level: 6,
    department: "fit-out",
    reportsTo: "1001,1002,1003,1004",
    status: "active",
    permissions: ["manage_projects", "assign_tasks", "view_reports"],
    roleColor: "#e67e22",
    hourlyRate: 140,
    notes: "Project Manager - Fit-out Department"
  },
  {
    id: 1011,
    firstName: "Murat",
    lastName: "Gökdemir",
    fullName: "Murat Gökdemir",
    initials: "MG",
    email: "murat.gokdemir@formulaint.com",
    phone: "+90 212 555 0111",
    username: "murat.gokdemir",
    position: "Technical Manager",
    role: "team_lead",
    level: 5,
    department: "mep",
    reportsTo: "1001,1002,1003,1004,1007",
    status: "active",
    permissions: ["manage_team_tasks", "view_team_reports"],
    roleColor: "#f39c12",
    hourlyRate: 120,
    notes: "Technical Manager - MEP Department"
  },
  {
    id: 1012,
    firstName: "Serra",
    lastName: "Uluveren",
    fullName: "Serra Uluveren",
    initials: "SU",
    email: "serra.uluveren@formulaint.com",
    phone: "+90 212 555 0112",
    username: "serra.uluveren",
    position: "Project Specialist",
    role: "senior",
    level: 4,
    department: "fit-out",
    reportsTo: "1001,1002,1003,1004",
    status: "active",
    permissions: ["create_tasks", "view_own_tasks"],
    roleColor: "#27ae60",
    hourlyRate: 100,
    notes: "Senior Project Specialist"
  },
  {
    id: 1013,
    firstName: "Ebru",
    lastName: "Alkın",
    fullName: "Ebru Alkın",
    initials: "EA",
    email: "ebru.alkin@formulaint.com",
    phone: "+90 212 555 0113",
    username: "ebru.alkin",
    position: "Site Chief",
    role: "senior",
    level: 4,
    department: "fit-out",
    reportsTo: "1001,1002,1003,1004",
    status: "active",
    permissions: ["create_tasks", "view_own_tasks"],
    roleColor: "#27ae60",
    hourlyRate: 100,
    notes: "Site Chief - Field Operations"
  },
  {
    id: 1014,
    firstName: "Uğur",
    lastName: "Karabayır",
    fullName: "Uğur Karabayır",
    initials: "UK",
    email: "ugur.karabayir@formulaint.com",
    phone: "+90 212 555 0114",
    username: "ugur.karabayir",
    position: "Technical Office Engineer",
    role: "junior",
    level: 3,
    department: "mep",
    reportsTo: "1001,1002,1003,1004,1007",
    status: "active",
    permissions: ["view_own_tasks"],
    roleColor: "#3498db",
    hourlyRate: 80,
    notes: "Technical Office Engineer - MEP Department"
  }
];

// Sample projects for seeding
const sampleProjects = [
  {
    id: 2001,
    name: "Akbank Head Office Renovation",
    type: "fit-out",
    description: "Complete renovation of Akbank headquarters including modern office spaces and meeting rooms",
    status: "active",
    priority: "high",
    clientName: "Akbank T.A.Ş.",
    clientContact: "Mehmet Yılmaz",
    clientEmail: "mehmet.yilmaz@akbank.com",
    budget: 2500000,
    location: "Levent, Istanbul",
    startDate: "2024-12-01",
    endDate: "2025-06-30",
    projectManager: 1008, // Kerem Salih Colak
    teamMembers: [1008, 1012, 1013],
    progress: 25,
    createdAt: "2024-12-01T00:00:00.000Z"
  },
  {
    id: 2002,
    name: "Garanti BBVA Tech Center MEP",
    type: "mep",
    description: "MEP infrastructure for new technology center including advanced cooling and electrical systems",
    status: "active",
    priority: "high",
    clientName: "Garanti BBVA",
    clientContact: "Ayşe Demir",
    clientEmail: "ayse.demir@garantibbva.com",
    budget: 1800000,
    location: "Ataşehir, Istanbul",
    startDate: "2024-11-15",
    endDate: "2025-05-15",
    projectManager: 1007, // Berk Ulukan
    teamMembers: [1007, 1011, 1014],
    progress: 40,
    createdAt: "2024-11-15T00:00:00.000Z"
  }
];

// Sample tasks for seeding
const sampleTasks = [
  {
    id: 3001,
    projectId: 2001,
    name: "Design Review and Approval",
    description: "Review architectural plans and get client approval for fit-out design",
    status: "completed",
    priority: "high",
    assignedTo: 1008,
    startDate: "2024-12-01",
    dueDate: "2024-12-15",
    progress: 100,
    estimatedHours: 40,
    actualHours: 38,
    createdAt: "2024-12-01T00:00:00.000Z"
  },
  {
    id: 3002,
    projectId: 2001,
    name: "Material Procurement",
    description: "Order and coordinate delivery of fit-out materials",
    status: "in_progress",
    priority: "high",
    assignedTo: 1012,
    startDate: "2024-12-15",
    dueDate: "2025-01-15",
    progress: 60,
    estimatedHours: 80,
    actualHours: 45,
    createdAt: "2024-12-15T00:00:00.000Z"
  },
  {
    id: 3003,
    projectId: 2002,
    name: "HVAC System Design",
    description: "Design heating, ventilation, and air conditioning systems for tech center",
    status: "completed",
    priority: "high",
    assignedTo: 1011,
    startDate: "2024-11-15",
    dueDate: "2024-12-15",
    progress: 100,
    estimatedHours: 120,
    actualHours: 118,
    createdAt: "2024-11-15T00:00:00.000Z"
  },
  {
    id: 3004,
    projectId: 2002,
    name: "Electrical Infrastructure Installation",
    description: "Install electrical panels and wiring for the data center",
    status: "in_progress",
    priority: "high",
    assignedTo: 1014,
    startDate: "2024-12-01",
    dueDate: "2025-02-28",
    progress: 30,
    estimatedHours: 200,
    actualHours: 55,
    createdAt: "2024-12-01T00:00:00.000Z"
  }
];

module.exports = {
  teamMembers: formulaEmployees,
  projects: sampleProjects,
  tasks: sampleTasks
};